FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
RUN apt update && apt install curl ffmpeg libsm6 libxext6  -y
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
WORKDIR /code
ENTRYPOINT /bin/bash -c "$HOME/.local/bin/uv run train_yolo11.py"
# ENTRYPOINT /bin/bash
# CMD ["uv", "run", "train_yolo11.py"]
